name: Programming for Linguists CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with Pylint
        run: |
          cd ..
          export PYTHONPATH=./programming-2021-19fpl
          python3 -m pylint programming-2021-19fpl --ignore=seminars
      - name: Test with unittest
        run: |
          python3 -m unittest discover -p "*_test.py"
